name: jasaivoy
description: "Proyecto integrador de 9°"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  http: ^1.2.2

  provider: ^6.1.2

  flutter_launcher_icons: ^0.14.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoJasaiVOY.png"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/logoJasaiVOY.png
    - assets/arrobaCorreo.png
    - assets/ImagenPasajero.png
    - assets/icons/IcoNavBar1.png
    - assets/icons/IcoNavBar2.png
    - assets/icons/IcoNavBar3.png
    - assets/icons/IcoNavBar4.png
    - assets/icons/IcoNavBar5.png
    - assets/icons/phone.png
    - assets/nombreIcono.png
    - assets/contraseñaIcono.png
    - assets/icons/IcoOcultarContraseña.png
    - assets/perfilFoto.png
    - assets/maps.png
    - assets/icons/IcoLocation.png